version: "3"

volumes:
  mongodb_data: {}

services:
  mongodb:
    image: mongo:3.6
    volumes:
      - mongodb_data:/data/db
    networks:
      - zappy_net
  
  django:
    image: mxahmed/zappy_service:latest
    ports:
      - 5000:5000
    depends_on:
      - mongodb
      - redis
    env_file: service/env
    networks:
      - zappy_net
 
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - zappy_net

  celery:
    image: mxahmed/zappy_service:latest
    env_file: service/env
    depends_on:
      - redis
      - mongodb
    command: celery -A conf.celery_app worker --loglevel=info
    networks:
      - zappy_net
  
  web:
    image: mxahmed/zappy_front:latest
    depends_on:
      - django
    ports:
      - 3000:80
    networks:
      - zappy_net

networks:
  zappy_net:
